import vegan from '~/assets/bay-leaf.svg';
import dessert from '~/assets/bread.svg';
import kids from '~/assets/child.svg';
import grill from '~/assets/dishwasher.svg';
import salad from '~/assets/eggplant.svg';
import second from '~/assets/frying-pan.svg';
import snack from '~/assets/healthy.svg';
import national from '~/assets/international.svg';
import medicine from '~/assets/kitchen_icon_24px.svg';
import sauce from '~/assets/mortar.svg';
import preparations from '~/assets/paste.svg';
import first from '~/assets/pot.svg';
import beverage from '~/assets/teacup.svg';

export const AccordionData = [
    {
        category: 'Салаты',
        href: '/salad',
        icon: salad,
        menu: ['Мясные салаты', 'Рыбные салаты', 'Овощные салаты', 'Теплые салаты'],
    },
    {
        category: 'Закуски',
        href: '/snacks',
        icon: snack,
        menu: [
            'Мясные закуски',
            'Рыбные закуски',
            'Овощные закуски',
            'Теплые закуски',
            'Бутерброды',
            'Фастфуд',
        ],
    },
    {
        category: 'Первые блюда',
        href: '/first-courses',
        icon: first,
        menu: ['Мясные супы', 'Овощные супы', 'Бульоны', 'Холодные супы', 'Диетические супы'],
    },
    {
        category: 'Вторые блюда',
        href: '/second-courses',
        icon: second,
        menu: [
            'Мясные',
            'Рыбные',
            'Овощные',
            'Из птицы',
            'Из грибов',
            'Из субпродуктов',
            'На пару',
            'Пельмени, вареники',
            'Мучные гарниры',
            'Овощные гарниры',
            'Пицца',
            'Суши',
        ],
    },
    {
        category: 'Десерты и выпечка',
        href: '/desserts',
        icon: dessert,
        menu: [
            'Блины и оладьи',
            'Пироги и пончики',
            'Торты',
            'Рулеты',
            'Кексы и маффины',
            'Сырники и ватрушки',
            'Из слоеного теста',
            'Из заварного теста',
            'Из дрожжевого теста',
            'Булочки и сдоба',
            'Хлеб',
            'Тесто на пиццу',
            'Кремы',
        ],
    },
    {
        category: 'Блюда на гриле',
        href: '/grilled',
        icon: grill,
        menu: ['Говядина', 'Свинина', 'Птица', 'Рыба', 'Грибы', 'Овощи'],
    },
    {
        category: 'Веганская кухня',
        href: '/vegan',
        icon: vegan,
        menu: [
            'Закуски',
            'Первые блюда',
            'Вторые блюда',
            'Гарниры',
            'Десерты',
            'Выпечка',
            'Сыроедческие блюда',
            'Напитки',
        ],
    },
    {
        category: 'Детские блюда',
        href: '/kids',
        icon: kids,
        menu: [
            'Первые блюда',
            'Вторые блюда',
            'Гарниры',
            'Выпечка',
            'Без глютена',
            'Без сахара',
            'Без аллергенов',
            'Блюда для прикорма',
        ],
    },
    {
        category: 'Лечебное питание',
        href: '/medicinal',
        icon: medicine,
        menu: [
            'Диета №1',
            'Диета №2',
            'Диета №3',
            'Диета №5',
            'Диета №6',
            'Диета №7',
            'Диета №8',
            'Диета №9',
            'Диета №10',
            'Диета №11',
            'Диета №12',
            'Диета №13',
            'Диета №14',
            'Без глютена',
            'Без аллергенов',
        ],
    },
    {
        category: 'Национальные',
        href: '/national',
        icon: national,
        menu: [
            'Американская кухня',
            'Армянская кухня',
            'Греческая кухня',
            'Грузинская кухня',
            'Итальянская кухня',
            'Испанская кухня',
            'Китайская кухня',
            'Мексиканская кухня',
            'Паназиатская кухня',
            'Русская кухня',
            'Турецкая кухня',
            'Французская кухня',
            'Шведская кухня',
            'Японская кухня',
            'Другая кухня',
        ],
    },
    {
        category: 'Соусы',
        href: '/sauces',
        icon: sauce,
        menu: ['Соусы мясные', 'Соусы сырные', 'Маринады'],
    },
    {
        category: 'Напитки',
        href: '/beverages',
        icon: beverage,
        menu: [
            'Соки и фреши',
            'Смузи',
            'Компоты',
            'Кисели',
            'Кофе',
            'Лечебный чай',
            'Квас',
            'Коктейли',
            'Алкогольные',
        ],
    },
    {
        category: 'Заготовки',
        href: '/preparations',
        icon: preparations,
        menu: [
            'Мясные заготовки',
            'Рыбные заготовки',
            'Из огурцов',
            'Из томатов',
            'Из грибов',
            'Овощные заготовки',
            'Салаты, икра',
            'Из фруктов и ягод',
        ],
    },
];
